# frozen_string_literal: true

require 'json'

namespace :icons do
  desc 'Generate lib/chroma_wave/icon_font/lucide_glyphs.rb from data/fonts/lucide-info.json'
  task :generate do
    info_path   = File.expand_path('../../data/fonts/lucide-info.json', __dir__)
    output_path = File.expand_path('../chroma_wave/icon_font/lucide_glyphs.rb', __dir__)

    abort "#{info_path} not found — download Lucide font assets first" unless File.exist?(info_path)

    data = JSON.parse(File.read(info_path))

    glyphs = data.each_with_object({}) do |(name, meta), hash|
      codepoint = meta['encodedCode'].delete_prefix('\\').to_i(16)
      hash[name.tr('-', '_')] = codepoint
    end

    lines = glyphs.sort.map { |name, cp| "      #{name.to_sym.inspect} => 0x#{cp.to_s(16).upcase}" }

    content = <<~RUBY
      # frozen_string_literal: true

      # Auto-generated by `rake icons:generate` from data/fonts/lucide-info.json.
      # Do not edit by hand.

      module ChromaWave
        class IconFont < Font
          LUCIDE_GLYPHS = {
      #{lines.join(",\n")}
          }.freeze
        end
      end
    RUBY

    File.write(output_path, content)
    puts "Generated #{output_path} (#{glyphs.size} glyphs)"
  end
end
