plugins:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

# Files that reopen ChromaWave to add require_relative or const_set calls
# are not missing documentation — the module is documented at its definition.
Style/Documentation:
  Exclude:
    - 'lib/chroma_wave/color.rb'
    - 'lib/chroma_wave/palette.rb'
    - 'lib/chroma_wave/pixel_format.rb'
    - 'lib/chroma_wave/framebuffer.rb'
    - 'lib/chroma_wave/canvas.rb'
    - 'lib/chroma_wave/layer.rb'

# Domain-standard short names used across graphics/geometry code.
# x0/y0/x1/y1 (line endpoints), xi/yi (midpoint iterators),
# sa/ea (start/end angles), sw (stroke width), lx/rx (left/right x).
Naming/MethodParameterName:
  AllowedNames:
    - r
    - g
    - b
    - a
    - x
    - y
    - w
    - h
    - c1
    - c2
    - cx
    - cy
    - rx
    - ry
    - sx
    - sy
    - dx
    - dy
    - ox
    - oy
    - x0
    - y0
    - x1
    - y1
    - xi
    - yi
    - sa
    - ea
    - sw
    - lx

# Drawing primitives require coordinate pairs, dimensions, and keyword
# options (stroke, fill, stroke_width) that cannot be meaningfully reduced.
Metrics/ParameterLists:
  Exclude:
    - 'lib/chroma_wave/drawing/primitives.rb'

# Alpha compositing, color distance, and drawing algorithms are inherently math-heavy.
# Splitting them further obscures the algorithm more than it clarifies.
Metrics/AbcSize:
  Exclude:
    - 'lib/chroma_wave/color.rb'
    - 'lib/chroma_wave/palette.rb'
    - 'lib/chroma_wave/drawing/primitives.rb'
    - 'lib/chroma_wave/canvas.rb'
    - 'lib/chroma_wave/surface.rb'

# Hex parsing, color distance, and drawing algorithms have inherent complexity.
Metrics/MethodLength:
  Exclude:
    - 'lib/chroma_wave/color.rb'
    - 'lib/chroma_wave/palette.rb'
    - 'lib/chroma_wave/drawing/primitives.rb'
    - 'lib/chroma_wave/canvas.rb'
    - 'lib/chroma_wave/surface.rb'

# Drawing primitives module contains many related algorithms that belong together.
# Canvas wraps a single String buffer and needs all RGBA methods in one class.
Metrics/ModuleLength:
  Exclude:
    - 'lib/chroma_wave/drawing/primitives.rb'
Metrics/ClassLength:
  Exclude:
    - 'lib/chroma_wave/canvas.rb'

# Scanline flood fill and ellipse algorithms have inherent branching complexity.
Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/chroma_wave/drawing/primitives.rb'
    - 'lib/chroma_wave/canvas.rb'
Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/chroma_wave/drawing/primitives.rb'
    - 'lib/chroma_wave/canvas.rb'

# DriverConfig has 16 fields; tests that construct configs need many lets.
# The default of 5 is too low for struct-heavy integration tests.
RSpec/MultipleMemoizedHelpers:
  Max: 15

# Value type specs naturally verify multiple properties of a single object.
# Splitting each attribute into its own example adds noise without clarity.
RSpec/MultipleExpectations:
  Max: 8

# Allow 5-deep nesting for drawing primitive specs with shape/mode/edge contexts.
RSpec/NestedGroups:
  Max: 5

# Drawing and compositing specs need extra lines for setup and pixel verification.
RSpec/ExampleLength:
  Max: 10

# LruCache#fetch requires a block (unlike Hash#fetch) — the block form
# is not redundant, it's the computation that runs on cache miss.
Style/RedundantFetchBlock:
  Exclude:
    - 'spec/chroma_wave/palette_spec.rb'
