# frozen_string_literal: true

require_relative 'opcodes'
require_relative 'driver_config'
require_relative 'header_generator/sequence_formatting'
require_relative 'header_generator/config_table_emitter'

module ChromaWave
  module DriverExtraction
    # Generates a C header file from an array of {DriverConfig} structs.
    #
    # The output includes init sequence arrays, a model configuration table,
    # and an +#ifndef+ include guard. The format matches the expected layout
    # of +driver_configs_generated.h+.
    #
    # @example
    #   generator = HeaderGenerator.new(configs)
    #   File.write('driver_configs_generated.h', generator.generate)
    class HeaderGenerator
      include Opcodes
      include SequenceFormatting
      include ConfigTableEmitter

      # @param configs [Array<DriverConfig>] extracted model configurations
      def initialize(configs)
        @configs = configs
      end

      # Generates the complete C header file content.
      #
      # @return [String] complete C header file content
      def generate
        lines = header_preamble
        @configs.each { |config| lines.concat(emit_init_arrays(config)) }
        lines.concat(emit_config_table)
        lines.concat(header_footer)
        lines.join("\n")
      end

      private

      # Returns the C header preamble lines.
      #
      # @return [Array<String>]
      def header_preamble
        tier2_count = @configs.count(&:tier2_reason)
        [
          '/* AUTO-GENERATED by script/extract_driver_configs.rb -- DO NOT EDIT */',
          "/* Models: #{@configs.length} total, #{tier2_count} tier2 */",
          '', '#ifndef DRIVER_CONFIGS_GENERATED_H', '#define DRIVER_CONFIGS_GENERATED_H',
          '', '#include "chroma_wave.h"', '#include "driver_registry.h"', ''
        ]
      end

      # Returns the C header footer lines.
      #
      # @return [Array<String>]
      def header_footer
        [
          '',
          '#define EPD_MODEL_COUNT (sizeof(epd_model_configs) / sizeof(epd_model_configs[0]))',
          '',
          '#endif /* DRIVER_CONFIGS_GENERATED_H */',
          ''
        ]
      end

      # Emits C array declarations for a config's init sequences.
      #
      # @param config [DriverConfig] the model config
      # @return [Array<String>]
      def emit_init_arrays(config)
        lines = emit_primary_init_array(config)
        emit_named_init_array(config, :init_fast_sequence, 'init_fast', lines)
        emit_named_init_array(config, :init_partial_sequence, 'init_partial', lines)
        lines
      end

      # Emits the primary init array with optional tier2 comment.
      #
      # @param config [DriverConfig] the model config
      # @return [Array<String>]
      def emit_primary_init_array(config)
        return [] unless config.init_sequence

        tier2 = config.tier2_reason ? " /* TIER2: #{config.tier2_reason} */" : ''
        [
          "static const uint8_t #{config.c_name}_init[] = {#{tier2}",
          format_init_sequence(config.init_sequence),
          '};',
          ''
        ]
      end

      # Emits a named init array if the sequence exists.
      #
      # @param config [DriverConfig] the model config
      # @param field [Symbol] sequence field name
      # @param suffix [String] C array name suffix
      # @param lines [Array<String>] output accumulator
      # @return [void]
      def emit_named_init_array(config, field, suffix, lines)
        seq = config.send(field)
        return unless seq

        lines << "static const uint8_t #{config.c_name}_#{suffix}[] = {"
        lines << format_init_sequence(seq)
        lines << '};'
        lines << ''
      end
    end
  end
end
